Data:
  dataset: celeba_dry
  batch_size: 600

Model:
  Unet:
    type: Unet
    kwargs:
      num_steps: 4000
      dim: 128
      dim_mults: [1, 2, 4, 8]
      dropout: 0.
  
  DiscreteDiffusion:
    type: DiscreteDiffusion
    kwargs:
      timesteps: 4000
    
max_steps: 1200000
lr: 0.00005
