model:
  embed_dim: 256
  n_embed: 1024 #323
  ddconfig:
    double_z: false
    z_channels: 256
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult:
    - 1
    - 1
    - 2
    - 2
    - 4
    num_res_blocks: 2
    attn_resolutions:
    - 16
    dropout: 0.0
  #ckpt_path: /home/hu/MultiDiff/vqgan/official/celeba_d.ckpt
  ckpt_path: /home/hu/MultiDiff/vqgan/official/in-1024.ckpt
  rs_weight: /home/hu/MultiDiff/vqgan/imgnet_emb_1024_16384.ckpt
  max_steps: 40000000
RS:
  false

Data:
  dataset: in
  batch_size: 5 #1GPU
